# 线上配置文件
# @author Floyd

spring:
    # DataSource Config
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: 'jdbc:mysql://124.222.82.27:3306/rivers_workflow?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true'
        username: rivers_workflow
        password: L53djizwaWdNNWJn
    activiti:
        database-schema-update: true
        db-history-used: true # 启动创建历史表
        history-level: full
        check-process-definitions: false # 是否自动检查 resources/processes 的流程定义文件
        # SMTP 服务
    # session 失效时间
    session:
        timeout: 86400
server:
    address: 0.0.0.0

mybatis:
    configuration:
        map-underscore-to-camel-case: true
    #        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-aliases-package: com.ocean.entity
    mapper-locations: classpath:mapper/**/*.xml

